### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by angrybrad** [lukeyouell/craft-randomkeygenerator#1]
More of a suggestion than anything... maybe consider going through Yii's Security class/methods?

Specifically https://github.com/yiisoft/yii2/blob/master/framework/base/Security.php#L455 and https://github.com/yiisoft/yii2/blob/master/framework/base/Security.php#L565

You might lose some of the finer-grained options like upper/lower/special/etc. characters, but you do get cryptographically secure, cross-platform keys.  A bit hacky, but you could probably apply some post-processing to the string depending on the options passed in.

Craft does has a way of generating non-cryptographically secure strings in StringHelper, too: https://github.com/craftcms/cms/blob/develop/src/helpers/StringHelper.php#L564-L604

**Comment by lukeyouell** [comment]
@angrybrad thanks! I'll look into those today.

The aim of the plugin was to recreate the functionality of randomkeygen.com (https://github.com/circlecell/randomkeygen.com/blob/master/js/index.js)

**Comment by angrybrad** [comment]
> The aim of the plugin was to recreate the functionality of randomkeygen.com 

Feel free to ignore me, then. :)
